version: '3'

services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
#    redis:
#      image: "redis:alpine"
  web:
    build: .
    volumes:
      - .:/curiosity
    ports:
      - "8000:8000"
    depends_on:
      - db
#      - redis
#  celery:
#    build: .
#    command: celery -A core worker -l info
#    depends_on:
#      - db
#      - redis
