version: '3'

volumes:
  pgdata:

services:
  postgres:
    image: postgres:11.3
    environment:
      POSTGRES_USER: curiosity
      POSTGRES_DB: curiosity
      POSTGRES_PASS: curiosity
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
  web:
    build: .
    volumes:
      - .:/curiosity
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  celery:
    build: .
    command: celery -A core worker -l info
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/curiosity
