apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: curiosity
        - name: POSTGRES_PASS
          value: curiosity
        - name: POSTGRES_USER
          value: curiosity
        image: postgres:11.3
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgdata
      restartPolicy: Always
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: pgdata
status: {}
